version: "3"

services:
  app:
    container_name: server
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    entrypoint: "/app/scripts/run/run_dev.sh"
    volumes:
      - ./server/src/:/app/src/
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      LOG_LEVEL: debug

  mongo:
    logging:
      driver: none
    volumes:
      - ./db_data_new:/data/db

  web:
    container_name: web
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    entrypoint: "/app/scripts/run/run_dev.sh"
    volumes:
      - ./client/src:/app/src/
      - ./client/public:/app/public/
    environment:
      NODE_ENV: development
